(function() {
  window.travelData = {
    places: [
      { region: "California", name: "San Diego", coords: [32.7157, -117.1611], spots: ["UC San Diego", "La Jolla Cove", "Balboa Park"] },
      { region: "California", name: "Los Angeles", coords: [34.0522, -118.2437], spots: ["Griffith Observatory", "Santa Monica Pier", "The Getty Center"] },
      { region: "California", name: "San Francisco", coords: [37.7749, -122.4194], spots: ["Golden Gate Bridge", "Fisherman's Wharf", "Pier 39"] },
      { region: "California", name: "Sacramento", coords: [38.5816, -121.4944], spots: ["California State Capitol", "Old Sacramento Waterfront"] },
      { region: "California", name: "Davis", coords: [38.5449, -121.7405], spots: ["UC Davis Arboretum", "Downtown Davis"] },
      { region: "California", name: "Santa Barbara", coords: [34.4208, -119.6982], spots: ["Stearns Wharf", "Santa Barbara County Courthouse"] },
      { region: "California", name: "Ventura", coords: [34.2746, -119.2290], spots: ["Ventura Pier", "Mission San Buenaventura"] },
      { region: "Texas", name: "Dallas", coords: [32.7767, -96.7970], spots: ["Dealey Plaza", "Reunion Tower", "Dallas Arts District"] },
      { region: "Texas", name: "Austin", coords: [30.2672, -97.7431], spots: ["Texas State Capitol", "Lady Bird Lake", "South Congress"] },
      {
        region: "Nevada",
        name: "Las Vegas",
        coords: [36.1699, -115.1398],
        spots: ["Arte Museum Las Vegas"],
        photos: [
          { src: "img/nevada/las-vegas-arte-museum-flower-lights.jpg", caption: "Arte Museum Las Vegas - Flower Lights" },
          { src: "img/nevada/las-vegas-arte-museum-floral-room.jpg", caption: "Arte Museum Las Vegas - Floral Room" },
          { src: "img/nevada/las-vegas-arte-museum-immersive-room.jpg", caption: "Arte Museum Las Vegas - Immersive Room" }
        ]
      },
      { region: "Washington", name: "Seattle", coords: [47.6062, -122.3321], spots: ["Space Needle", "Pike Place Market", "Seattle Waterfront"] },
      { region: "New York", name: "New York City", coords: [40.7128, -74.0060], spots: ["Times Square", "Central Park", "Brooklyn Bridge"] },
      { region: "New York", name: "Ithaca", coords: [42.4430, -76.5019], spots: ["Cornell University", "Ithaca Commons", "Ithaca Falls"] },
      { region: "District of Columbia", name: "Washington, D.C.", coords: [38.9072, -77.0369], spots: ["National Mall", "Lincoln Memorial", "U.S. Capitol"] },
      { region: "Australia", name: "Sydney", coords: [-33.8688, 151.2093], spots: ["Sydney Opera House", "Harbour Bridge", "Darling Harbour"] },
      { region: "Singapore", name: "Singapore", localName: "新加坡", coords: [1.3521, 103.8198], spots: ["Marina Bay Sands", "Gardens by the Bay", "Merlion Park"] },
      { region: "Japan", name: "Kyoto", localName: "京都", coords: [35.0116, 135.7681], spots: ["Kiyomizu-dera", "Fushimi Inari Taisha", "Arashiyama"], spotsLocal: ["清水寺", "伏見稲荷大社", "嵐山"] },
      {
        region: "Japan",
        name: "Osaka",
        localName: "大阪",
        coords: [34.6937, 135.5023],
        spots: ["Osaka City Museum of Fine Arts", "Keitakuen Garden", "River Tower View", "Dotonbori", "Shitennoji Temple", "Tennoji Zoo", "Shinsekai", "Tsutenkaku", "Nagai Botanical Garden", "Nagai Park"],
        spotsLocal: ["大阪市立美術館", "慶沢園", "River Tower View", "道頓堀", "四天王寺", "天王寺動物園", "新世界", "通天閣", "長居植物園", "長居公園"],
        photos: [
          { src: "img/japan/osaka-city-museum-city-view.jpg", caption: "Osaka City Museum of Fine Arts - City View" },
          { src: "img/japan/osaka-keitakuen-garden-bridge.jpg", caption: "Keitakuen Garden - Bridge" },
          { src: "img/japan/osaka-keitakuen-autumn-maples.jpg", caption: "Keitakuen Garden - Autumn Maples" },
          { src: "img/japan/osaka-keitakuen-garden-reflection.jpg", caption: "Keitakuen Garden - Reflection" },
          { src: "img/japan/osaka-keitakuen-water-reflection.jpg", caption: "Keitakuen Garden - Water Reflection" },
          { src: "img/japan/osaka-keitakuen-maple-leaves.jpg", caption: "Keitakuen Garden - Maple Leaves" },
          { src: "img/japan/osaka-river-tower-sunset-skyline.jpg", caption: "River Tower View - Sunset Skyline" },
          { src: "img/japan/osaka-river-tower-window-view.jpg", caption: "River Tower View - Window View" },
          { src: "img/japan/osaka-shitennoji-five-story-pagoda.jpg", caption: "Shitennoji Temple - Five-story Pagoda" },
          { src: "img/japan/osaka-tennoji-zoo-habitat-waterfall.jpg", caption: "Tennoji Zoo - Habitat Waterfall" },
          { src: "img/japan/osaka-tennoji-zoo-deer.jpg", caption: "Tennoji Zoo - Deer" },
          { src: "img/japan/osaka-tennoji-zoo-zebra.jpg", caption: "Tennoji Zoo - Zebra" },
          { src: "img/japan/osaka-tennoji-zoo-flamingos.jpg", caption: "Tennoji Zoo - Flamingos" },
          { src: "img/japan/osaka-tennoji-zoo-tiger.jpg", caption: "Tennoji Zoo - Tiger" },
          { src: "img/japan/osaka-shinsekai-tsutenkaku.jpg", caption: "Shinsekai - Tsutenkaku" },
          { src: "img/japan/osaka-nagai-botanical-waterfall.jpg", caption: "Nagai Botanical Garden - Waterfall" },
          { src: "img/japan/osaka-nagai-botanical-camellia.jpg", caption: "Nagai Botanical Garden - Camellia" },
          { src: "img/japan/osaka-nagai-botanical-autumn-leaves.jpg", caption: "Nagai Botanical Garden - Autumn Leaves" },
          { src: "img/japan/osaka-nagai-botanical-winter-garden.jpg", caption: "Nagai Botanical Garden - Winter Garden" },
          { src: "img/japan/osaka-nagai-botanical-white-blossoms.jpg", caption: "Nagai Botanical Garden - White Blossoms" },
          { src: "img/japan/osaka-nagai-botanical-red-bridge.jpg", caption: "Nagai Botanical Garden - Red Bridge" },
          { src: "img/japan/osaka-nagai-botanical-tree-path.jpg", caption: "Nagai Botanical Garden - Tree Path" },
          { src: "img/japan/osaka-nagai-botanical-branches.jpg", caption: "Nagai Botanical Garden - Branches" },
          { src: "img/japan/osaka-nagai-botanical-cherry-blossoms.jpg", caption: "Nagai Botanical Garden - Cherry Blossoms" },
          { src: "img/japan/osaka-nagai-botanical-lake-fountain.jpg", caption: "Nagai Botanical Garden - Lake Fountain" },
          { src: "img/japan/osaka-nagai-botanical-water-view.jpg", caption: "Nagai Botanical Garden - Water View" }
        ]
      },
      { region: "Japan", name: "Otaru, Hokkaido", localName: "小樽, 北海道", coords: [43.1907, 140.9947], spots: ["Otaru Canal", "Sakaimachi Street", "Otaru Music Box Museum"], spotsLocal: ["小樽運河", "堺町通り", "小樽オルゴール堂"] },
      { region: "Japan", name: "Yoichi, Hokkaido", localName: "余市, 北海道", coords: [43.1951, 140.7835], spots: ["Nikka Whisky Yoichi Distillery", "Yoichi Port"], spotsLocal: ["ニッカウヰスキー余市蒸溜所", "余市港"] },
      { region: "Brunei", name: "Bandar Seri Begawan", localName: "بندر سري بڬاوان", coords: [4.9031, 114.9398], spots: ["Sultan Omar Ali Saifuddien Mosque", "Kampong Ayer", "Royal Regalia Museum"], spotsLocal: ["Masjid Omar Ali Saifuddien", "كامڤوڠ اير", "Muzium Alat Kebesaran Diraja"] },
      { region: "Malaysia", name: "Kuala Lumpur", localName: "كوالا لومڤور", coords: [3.1390, 101.6869], spots: ["Petronas Twin Towers", "Batu Caves", "Merdeka Square"], spotsLocal: ["Menara Berkembar Petronas", "Gua Batu", "Dataran Merdeka"] },
      { region: "Malaysia", name: "Johor Bahru", localName: "جوهر بهرو", coords: [1.4927, 103.7414], spots: ["Sultan Abu Bakar Mosque", "Johor Bahru City Square", "Danga Bay"], spotsLocal: ["Masjid Sultan Abu Bakar", "Johor Bahru City Square", "Teluk Danga"] },
      {
        region: "Laos",
        name: "Vientiane",
        localName: "ວຽງຈັນ",
        coords: [17.9757, 102.6331],
        spots: ["Pha That Luang", "Patuxai", "Wat Sisaket"],
        spotsLocal: ["ພຣະທາດຫຼວງ", "ປະຕູໄຊ", "ວັດສີສະເກດ"],
        photos: [
          { src: "img/laos/vientiane-patuxai-monument-front.jpg", caption: "Vientiane / ວຽງຈັນ - Patuxai / ປະຕູໄຊ - Monument Front" },
          { src: "img/laos/vientiane-patuxai-arch-detail.jpg", caption: "Vientiane / ວຽງຈັນ - Patuxai / ປະຕູໄຊ - Arch Detail" },
          { src: "img/laos/vientiane-pha-that-luang-golden-stupa-detail.jpg", caption: "Vientiane / ວຽງຈັນ - Pha That Luang / ພຣະທາດຫຼວງ - Golden Stupa Detail" },
          { src: "img/laos/vientiane-pha-that-luang-golden-stupa.jpg", caption: "Vientiane / ວຽງຈັນ - Pha That Luang / ພຣະທາດຫຼວງ - Golden Stupa" },
          { src: "img/laos/vientiane-pha-that-luang-silhouette.jpg", caption: "Vientiane / ວຽງຈັນ - Pha That Luang / ພຣະທາດຫຼວງ - Silhouette" }
        ]
      },
      {
        region: "Cambodia",
        name: "Phnom Penh",
        localName: "ភ្នំពេញ",
        coords: [11.5564, 104.9282],
        spots: ["Royal Palace", "Silver Pagoda", "National Museum of Cambodia", "Independence Monument", "Wat Phnom", "Tuol Sleng Genocide Museum", "Choeung Ek Genocidal Center", "Riverside"],
        spotsLocal: ["ព្រះបរមរាជវាំង", "វត្តព្រះកែវមរកត", "សារមន្ទីរជាតិ", "វិមានឯករាជ្យ", "វត្តភ្នំ", "សារមន្ទីរប្រល័យពូជសាសន៍ទួលស្លែង", "មជ្ឈមណ្ឌលប្រល័យពូជសាសន៍ជើងឯក", "មាត់ទន្លេ"],
        photos: [
          { src: "img/cambodia/phnom-penh-royal-palace-garden-walk.jpg", caption: "Phnom Penh / ភ្នំពេញ - Royal Palace - Garden Walk" },
          { src: "img/cambodia/phnom-penh-royal-palace-roof-detail.jpg", caption: "Phnom Penh / ភ្នំពេញ - Royal Palace - Roof Detail" },
          { src: "img/cambodia/phnom-penh-royal-palace-throne-hall.jpg", caption: "Phnom Penh / ភ្នំពេញ - Royal Palace - Throne Hall" },
          { src: "img/cambodia/phnom-penh-royal-palace-spire.jpg", caption: "Phnom Penh / ភ្នំពេញ - Royal Palace - Spire" },
          { src: "img/cambodia/phnom-penh-silver-pagoda-white-stupa.jpg", caption: "Phnom Penh / ភ្នំពេញ - Silver Pagoda - White Stupa" },
          { src: "img/cambodia/phnom-penh-silver-pagoda-stupa-statue.jpg", caption: "Phnom Penh / ភ្នំពេញ - Silver Pagoda - Stupa Statue" },
          { src: "img/cambodia/phnom-penh-royal-palace-temple-roof.jpg", caption: "Phnom Penh / ភ្នំពេញ - Royal Palace - Temple Roof" },
          { src: "img/cambodia/phnom-penh-national-museum-gallery.jpg", caption: "Phnom Penh / ភ្នំពេញ - National Museum - Gallery" },
          { src: "img/cambodia/phnom-penh-national-museum-courtyard-pond.jpg", caption: "Phnom Penh / ភ្នំពេញ - National Museum - Courtyard Pond" },
          { src: "img/cambodia/phnom-penh-national-museum-flag-detail.jpg", caption: "Phnom Penh / ភ្នំពេញ - National Museum - Flag Detail" },
          { src: "img/cambodia/phnom-penh-street-balconies.jpg", caption: "Phnom Penh / ភ្នំពេញ - Street Balconies" },
          { src: "img/cambodia/phnom-penh-riverside-pigeons.jpg", caption: "Phnom Penh / ភ្នំពេញ - Riverside Pigeons" },
          { src: "img/cambodia/phnom-penh-mekong-river-skyline.jpg", caption: "Phnom Penh / ភ្នំពេញ - Mekong River Skyline" },
          { src: "img/cambodia/phnom-penh-river-birds.jpg", caption: "Phnom Penh / ភ្នំពេញ - River Birds" },
          { src: "img/cambodia/phnom-penh-independence-monument.jpg", caption: "Phnom Penh / ភ្នំពេញ - Independence Monument" },
          { src: "img/cambodia/phnom-penh-evening-traffic.jpg", caption: "Phnom Penh / ភ្នំពេញ - Evening Traffic" },
          { src: "img/cambodia/phnom-penh-city-skyline.jpg", caption: "Phnom Penh / ភ្នំពេញ - City Skyline" },
          { src: "img/cambodia/phnom-penh-wat-phnom-white-stupa.jpg", caption: "Phnom Penh / ភ្នំពេញ - Wat Phnom - White Stupa" },
          { src: "img/cambodia/phnom-penh-wat-phnom-shrine-entrance.jpg", caption: "Phnom Penh / ភ្នំពេញ - Wat Phnom - Shrine Entrance" },
          { src: "img/cambodia/phnom-penh-tuol-sleng-corridor.jpg", caption: "Phnom Penh / ភ្នំពេញ - Tuol Sleng - Corridor" },
          { src: "img/cambodia/phnom-penh-tuol-sleng-room.jpg", caption: "Phnom Penh / ភ្នំពេញ - Tuol Sleng - Room" },
          { src: "img/cambodia/phnom-penh-tuol-sleng-artwork.jpg", caption: "Phnom Penh / ភ្នំពេញ - Tuol Sleng - Artwork" },
          { src: "img/cambodia/phnom-penh-tuol-sleng-drawing.jpg", caption: "Phnom Penh / ភ្នំពេញ - Tuol Sleng - Drawing" },
          { src: "img/cambodia/phnom-penh-tuol-sleng-exhibit-wall.jpg", caption: "Phnom Penh / ភ្នំពេញ - Tuol Sleng - Exhibit Wall" },
          { src: "img/cambodia/phnom-penh-tuol-sleng-cell-block.jpg", caption: "Phnom Penh / ភ្នំពេញ - Tuol Sleng - Cell Block" },
          { src: "img/cambodia/phnom-penh-choeung-ek-fields-skyline.jpg", caption: "Phnom Penh / ភ្នំពេញ - Choeung Ek - Fields and Skyline" },
          { src: "img/cambodia/phnom-penh-choeung-ek-memorial-quote.jpg", caption: "Phnom Penh / ភ្នំពេញ - Choeung Ek - Memorial Quote" },
          { src: "img/cambodia/phnom-penh-choeung-ek-memorial-stupa.jpg", caption: "Phnom Penh / ភ្នំពេញ - Choeung Ek - Memorial Stupa" },
          { src: "img/cambodia/phnom-penh-choeung-ek-remembrance-tree.jpg", caption: "Phnom Penh / ភ្នំពេញ - Choeung Ek - Remembrance Tree" },
          { src: "img/cambodia/phnom-penh-choeung-ek-memorial-statue.jpg", caption: "Phnom Penh / ភ្នំពេញ - Choeung Ek - Memorial Statue" },
          { src: "img/cambodia/phnom-penh-riverside-cattle.jpg", caption: "Phnom Penh / ភ្នំពេញ - Riverside Cattle" }
        ]
      },
      { region: "Indonesia", name: "Batam", localName: "Kota Batam", coords: [1.0456, 104.0305], spots: ["Barelang Bridge", "Maha Vihara Duta Maitreya", "Nagoya Hill"], spotsLocal: ["Jembatan Barelang", "Maha Vihara Duta Maitreya", "Nagoya Hill"] },
      {
        region: "Vietnam",
        name: "Ho Chi Minh City",
        localName: "Thành phố Hồ Chí Minh",
        coords: [10.8231, 106.6297],
        spots: ["Ben Thanh Market", "Central Post Office", "Ho Chi Minh City Museum", "Notre-Dame Cathedral Basilica", "City Streets"],
        spotsLocal: ["Chợ Bến Thành", "Bưu điện Trung tâm Sài Gòn", "Bảo tàng Thành phố Hồ Chí Minh", "Nhà thờ Đức Bà Sài Gòn", "Đường phố"],
        photos: [
          { src: "img/vietnam/ho-chi-minh-city-museum-historical-photo.jpg", caption: "Ho Chi Minh City / Thành phố Hồ Chí Minh - Museum Historical Photo" },
          { src: "img/vietnam/ho-chi-minh-city-museum-inscription.jpg", caption: "Ho Chi Minh City / Thành phố Hồ Chí Minh - Museum Inscription" },
          { src: "img/vietnam/ho-chi-minh-city-museum-facade.jpg", caption: "Ho Chi Minh City / Thành phố Hồ Chí Minh - Museum Facade" },
          { src: "img/vietnam/ho-chi-minh-city-park-gate.jpg", caption: "Ho Chi Minh City / Thành phố Hồ Chí Minh - Park Gate" },
          { src: "img/vietnam/ho-chi-minh-city-central-post-office-exterior.jpg", caption: "Ho Chi Minh City / Thành phố Hồ Chí Minh - Central Post Office Exterior" },
          { src: "img/vietnam/ho-chi-minh-city-central-post-office-interior.jpg", caption: "Ho Chi Minh City / Thành phố Hồ Chí Minh - Central Post Office Interior" },
          { src: "img/vietnam/ho-chi-minh-city-ben-thanh-market-hats.jpg", caption: "Ho Chi Minh City / Thành phố Hồ Chí Minh - Ben Thanh Market Hats" },
          { src: "img/vietnam/ho-chi-minh-city-alley.jpg", caption: "Ho Chi Minh City / Thành phố Hồ Chí Minh - Alley" },
          { src: "img/vietnam/ho-chi-minh-city-night-skyline.jpg", caption: "Ho Chi Minh City / Thành phố Hồ Chí Minh - Night Skyline" }
        ]
      },
      {
        region: "Vietnam",
        name: "Hanoi",
        localName: "Hà Nội",
        coords: [21.0278, 105.8342],
        spots: ["Hoan Kiem Lake", "Old Quarter", "St. Joseph's Cathedral", "Temple of Literature", "Vietnam Fine Arts Museum"],
        spotsLocal: ["Hồ Hoàn Kiếm", "Phố cổ Hà Nội", "Nhà thờ Lớn Hà Nội", "Văn Miếu", "Bảo tàng Mỹ thuật Việt Nam"],
        photos: [
          { src: "img/vietnam/hanoi-old-quarter-lanterns-building.jpg", caption: "Hanoi - Old Quarter Lanterns" },
          { src: "img/vietnam/hanoi-old-quarter-red-lanterns.jpg", caption: "Hanoi - Old Quarter Red Lanterns" },
          { src: "img/vietnam/hanoi-st-joseph-cathedral.jpg", caption: "Hanoi - St. Joseph's Cathedral" },
          { src: "img/vietnam/hanoi-hoan-kiem-lake-turtle-tower.jpg", caption: "Hanoi - Hoan Kiem Lake Turtle Tower" },
          { src: "img/vietnam/hanoi-hoan-kiem-lake-shore.jpg", caption: "Hanoi - Hoan Kiem Lake Shore" },
          { src: "img/vietnam/hanoi-hoan-kiem-lake-flowers.jpg", caption: "Hanoi - Hoan Kiem Lake Flowers" },
          { src: "img/vietnam/hanoi-lenin-statue.jpg", caption: "Hanoi - Lenin Statue" },
          { src: "img/vietnam/hanoi-flag-tower.jpg", caption: "Hanoi - Flag Tower" },
          { src: "img/vietnam/hanoi-military-history-museum-aircraft.jpg", caption: "Hanoi - Military History Museum Aircraft" },
          { src: "img/vietnam/hanoi-war-memorial-monument.jpg", caption: "Hanoi - War Memorial Monument" },
          { src: "img/vietnam/hanoi-temple-of-literature-gate.jpg", caption: "Hanoi - Temple of Literature Gate" },
          { src: "img/vietnam/hanoi-ho-chi-minh-mausoleum.jpg", caption: "Hanoi - Ho Chi Minh Mausoleum" },
          { src: "img/vietnam/hanoi-museum-facade.jpg", caption: "Hanoi - Museum Facade" },
          { src: "img/vietnam/hanoi-fine-arts-museum-building.jpg", caption: "Hanoi - Fine Arts Museum Building" },
          { src: "img/vietnam/hanoi-fine-arts-museum-gallery.jpg", caption: "Hanoi - Fine Arts Museum Gallery" },
          { src: "img/vietnam/hanoi-fine-arts-painting-harbor.jpg", caption: "Hanoi - Fine Arts Painting Harbor" },
          { src: "img/vietnam/hanoi-fine-arts-painting-scene.jpg", caption: "Hanoi - Fine Arts Painting Scene" },
          { src: "img/vietnam/hanoi-fine-arts-lacquer-panel.jpg", caption: "Hanoi - Fine Arts Lacquer Panel" },
          { src: "img/vietnam/hanoi-fine-arts-museum-interior.jpg", caption: "Hanoi - Fine Arts Museum Interior" },
          { src: "img/vietnam/hanoi-hoan-kiem-lake-yellow-colonial-building.jpg", caption: "Hoan Kiem Lake / Hồ Hoàn Kiếm - Yellow Colonial Building" },
          { src: "img/vietnam/hanoi-old-gate.jpg", caption: "Hanoi - Old Gate" },
          { src: "img/vietnam/hanoi-one-pillar-pagoda.jpg", caption: "Hanoi - One Pillar Pagoda" },
          { src: "img/vietnam/hanoi-temple-gate.jpg", caption: "Hanoi - Temple Gate" }
        ]
      },
      { region: "Thailand", name: "Bangkok", localName: "กรุงเทพฯ", coords: [13.7563, 100.5018], spots: ["Grand Palace", "Wat Arun", "Wat Pho"], spotsLocal: ["พระบรมมหาราชวัง", "วัดอรุณ", "วัดโพธิ์"] },
      {
        region: "Taiwan",
        name: "Taipei",
        localName: "臺北",
        coords: [25.0330, 121.5654],
        spots: ["The Grand Hotel"],
        spotsLocal: ["圓山大飯店"],
        photos: [
          { src: "img/taiwan/grand-hotel-taipei-christmas-tree.jpg", caption: "Taipei - The Grand Hotel Christmas Tree" },
          { src: "img/taiwan/grand-hotel-taipei-ceiling.jpg", caption: "Taipei - The Grand Hotel Ceiling" },
          { src: "img/taiwan/grand-hotel-taipei-rainy-skyline.jpg", caption: "Taipei - The Grand Hotel / 圓山大飯店 - Rainy Skyline" }
        ]
      },
      { region: "Taiwan", name: "Hualien", localName: "花蓮", coords: [23.9872, 121.6015], spots: ["Taroko Gorge", "Qixingtan Beach"], spotsLocal: ["太魯閣", "七星潭"] },
      { region: "Taiwan", name: "Hsinchu", localName: "新竹", coords: [24.8138, 120.9675], spots: ["Hsinchu City God Temple", "East Gate"], spotsLocal: ["新竹都城隍廟", "迎曦門"] },
      {
        region: "Taiwan",
        name: "Nantou",
        localName: "南投",
        coords: [23.8656, 120.9159],
        spots: ["Sun Moon Lake"],
        spotsLocal: ["日月潭"],
        photos: [
          { src: "img/taiwan/sun-moon-lake-lake-view.jpg", caption: "Sun Moon Lake / 日月潭 - Lake View" },
          { src: "img/taiwan/sun-moon-lake-trail.jpg", caption: "Sun Moon Lake / 日月潭 - Trail" },
          { src: "img/taiwan/sun-moon-lake-temple-view.jpg", caption: "Sun Moon Lake / 日月潭 - Temple View" },
          { src: "img/taiwan/sun-moon-lake-pagoda-view.jpg", caption: "Sun Moon Lake / 日月潭 - Pagoda View" },
          { src: "img/taiwan/sun-moon-lake-lakeside-sculpture.jpg", caption: "Sun Moon Lake / 日月潭 - Lakeside Sculpture" }
        ]
      },
      {
        region: "Taiwan",
        name: "Tainan",
        localName: "臺南",
        coords: [22.9999, 120.2270],
        spots: ["Chihkan Tower", "Anping Old Fort", "Chimei Museum"],
        spotsLocal: ["赤崁樓", "安平古堡", "奇美博物館"],
        photos: [
          { src: "img/taiwan/chimei-museum-interior.jpg", caption: "Chimei Museum - Interior" },
          { src: "img/taiwan/chimei-museum-exterior.jpg", caption: "Chimei Museum - Exterior" },
          { src: "img/taiwan/anping-fort-watchtower.jpg", caption: "Anping Old Fort - Watchtower" }
        ]
      },
      { region: "Taiwan", name: "Kaohsiung", localName: "高雄", coords: [22.6273, 120.3014], spots: ["Lotus Pond", "Pier-2 Art Center"], spotsLocal: ["蓮池潭", "駁二藝術特區"] },
      {
        region: "Yunnan",
        name: "Kunming",
        localName: "昆明",
        coords: [25.0389, 102.7183],
        spots: ["Dianchi Lake", "Stone Forest", "Green Lake Park"],
        spotsLocal: ["滇池", "石林", "翠湖公园"],
        photos: [
          { src: "img/yunnan/kunming-garden-lake-view.jpg", caption: "Kunming / 昆明 - Garden Lake View" },
          { src: "img/yunnan/kunming-stone-forest-rock-window.jpg", caption: "Kunming / 昆明 - Stone Forest / 石林 - Rock Window" },
          { src: "img/yunnan/kunming-stone-forest-karst-passage.jpg", caption: "Kunming / 昆明 - Stone Forest / 石林 - Karst Passage" },
          { src: "img/yunnan/kunming-stone-forest-mossy-path.jpg", caption: "Kunming / 昆明 - Stone Forest / 石林 - Mossy Path" }
        ]
      },
      {
        region: "Yunnan",
        name: "Dali",
        localName: "大理",
        coords: [25.6065, 100.2676],
        spots: ["Erhai Lake"],
        spotsLocal: ["洱海"],
        photos: [
          { src: "img/yunnan/dali-erhai-lake-mountain-horizon.jpg", caption: "Dali / 大理 - Erhai Lake / 洱海 - Mountain Horizon" },
          { src: "img/yunnan/dali-erhai-lake-lakeside-view.jpg", caption: "Dali / 大理 - Erhai Lake / 洱海 - Lakeside View" },
          { src: "img/yunnan/dali-erhai-lake-water-and-mountains.jpg", caption: "Dali / 大理 - Erhai Lake / 洱海 - Water and Mountains" }
        ]
      },
      {
        region: "Yunnan",
        name: "Lijiang",
        localName: "丽江",
        coords: [26.8721, 100.2296],
        spots: ["Lijiang Old Town", "Jade Dragon Snow Mountain", "Blue Moon Valley", "Black Dragon Pool"],
        spotsLocal: ["丽江古城", "玉龙雪山", "蓝月谷", "黑龙潭"],
        photos: [
          { src: "img/yunnan/lijiang-jade-dragon-snow-mountain-highland-meadow.jpg", caption: "Lijiang / 丽江 - Jade Dragon Snow Mountain / 玉龙雪山 - Highland Meadow" },
          { src: "img/yunnan/lijiang-jade-dragon-snow-mountain-yak-trail.jpg", caption: "Lijiang / 丽江 - Jade Dragon Snow Mountain / 玉龙雪山 - Yak Trail" },
          { src: "img/yunnan/lijiang-jade-dragon-snow-mountain-cloudy-meadow.jpg", caption: "Lijiang / 丽江 - Jade Dragon Snow Mountain / 玉龙雪山 - Cloudy Meadow" },
          { src: "img/yunnan/lijiang-jade-dragon-snow-mountain-forest-walk.jpg", caption: "Lijiang / 丽江 - Jade Dragon Snow Mountain / 玉龙雪山 - Forest Walk" },
          { src: "img/yunnan/lijiang-jade-dragon-snow-mountain-valley-view.jpg", caption: "Lijiang / 丽江 - Jade Dragon Snow Mountain / 玉龙雪山 - Valley View" },
          { src: "img/yunnan/lijiang-blue-moon-valley-turquoise-water.jpg", caption: "Lijiang / 丽江 - Blue Moon Valley / 蓝月谷 - Turquoise Water" },
          { src: "img/yunnan/lijiang-blue-moon-valley-waterfall-steps.jpg", caption: "Lijiang / 丽江 - Blue Moon Valley / 蓝月谷 - Waterfall Steps" },
          { src: "img/yunnan/lijiang-jade-dragon-snow-mountain-forest-canopy.jpg", caption: "Lijiang / 丽江 - Jade Dragon Snow Mountain / 玉龙雪山 - Forest Canopy" },
          { src: "img/yunnan/lijiang-blue-moon-valley-clear-pool.jpg", caption: "Lijiang / 丽江 - Blue Moon Valley / 蓝月谷 - Clear Pool" },
          { src: "img/yunnan/lijiang-blue-moon-valley-mountain-stream.jpg", caption: "Lijiang / 丽江 - Blue Moon Valley / 蓝月谷 - Mountain Stream" },
          { src: "img/yunnan/lijiang-jade-dragon-snow-mountain-glacier.jpg", caption: "Lijiang / 丽江 - Jade Dragon Snow Mountain / 玉龙雪山 - Glacier" },
          { src: "img/yunnan/lijiang-jade-dragon-snow-mountain-glacier-view.jpg", caption: "Lijiang / 丽江 - Jade Dragon Snow Mountain / 玉龙雪山 - Glacier View" },
          { src: "img/yunnan/lijiang-jade-dragon-snow-mountain-misty-peak.jpg", caption: "Lijiang / 丽江 - Jade Dragon Snow Mountain / 玉龙雪山 - Misty Peak" },
          { src: "img/yunnan/lijiang-evening-city-view.jpg", caption: "Lijiang / 丽江 - Evening City View" },
          { src: "img/yunnan/lijiang-mountain-city-view.jpg", caption: "Lijiang / 丽江 - Mountain City View" }
        ]
      },
      {
        region: "Guizhou",
        name: "Guiyang",
        localName: "贵阳",
        coords: [26.6470, 106.6302],
        spots: ["Xifeng Concentration Camp"],
        spotsLocal: ["息烽集中营"],
        photos: [
          { src: "img/guizhou/guiyang-memorial-grounds.jpg", caption: "Guiyang / 贵阳 - Memorial Grounds" },
          { src: "img/guizhou/guiyang-temple-courtyard.jpg", caption: "Guiyang / 贵阳 - Temple Courtyard" },
          { src: "img/guizhou/guiyang-xifeng-concentration-camp.jpg", caption: "Guiyang / 贵阳 - Xifeng Concentration Camp / 息烽集中营" }
        ]
      },
      {
        region: "Guizhou",
        name: "Zunyi",
        localName: "遵义",
        coords: [27.7257, 106.9274],
        spots: ["Zunyi Conference Site", "Hongjun Mountain", "Historical Exhibition"],
        spotsLocal: ["遵义会议会址", "红军山", "历史展陈"],
        photos: [
          { src: "img/guizhou/zunyi-historical-exhibition.jpg", caption: "Zunyi / 遵义 - Historical Exhibition" },
          { src: "img/guizhou/zunyi-city-view.jpg", caption: "Zunyi / 遵义 - City View" },
          { src: "img/guizhou/zunyi-historical-document.jpg", caption: "Zunyi / 遵义 - Historical Document" },
          { src: "img/guizhou/zunyi-exhibition-detail.jpg", caption: "Zunyi / 遵义 - Exhibition Detail" },
          { src: "img/guizhou/zunyi-museum-artifact.jpg", caption: "Zunyi / 遵义 - Museum Artifact" },
          { src: "img/guizhou/zunyi-mao-zedong-residence.jpg", caption: "Zunyi / 遵义 - Mao Zedong Residence / 毛泽东住居" },
          { src: "img/guizhou/zunyi-conference-site.jpg", caption: "Zunyi / 遵义 - Zunyi Conference Site / 遵义会议会址" }
        ]
      },
      {
        region: "Guizhou",
        name: "Renhuai",
        localName: "仁怀",
        coords: [27.7926, 106.4012],
        spots: ["Maotai Town", "Chishui River", "Maotai Distillery"],
        spotsLocal: ["茅台镇", "赤水河", "茅台酒厂"],
        photos: [
          { src: "img/guizhou/renhuai-maotai-town-river-valley.jpg", caption: "Renhuai / 仁怀 - Maotai Town / 茅台镇 - River Valley" },
          { src: "img/guizhou/renhuai-maotai-town-hillside-view.jpg", caption: "Renhuai / 仁怀 - Maotai Town / 茅台镇 - Hillside View" },
          { src: "img/guizhou/renhuai-maotai-town-mountain-town.jpg", caption: "Renhuai / 仁怀 - Maotai Town / 茅台镇 - Mountain Town" },
          { src: "img/guizhou/renhuai-maotai-town-red-bridge.jpg", caption: "Renhuai / 仁怀 - Maotai Town / 茅台镇 - Red Bridge" },
          { src: "img/guizhou/renhuai-maotai-town-riverside-buildings.jpg", caption: "Renhuai / 仁怀 - Maotai Town / 茅台镇 - Riverside Buildings" },
          { src: "img/guizhou/renhuai-maotai-town-green-hills.jpg", caption: "Renhuai / 仁怀 - Maotai Town / 茅台镇 - Green Hills" }
        ]
      },
      {
        region: "Guizhou",
        name: "Anshun",
        localName: "安顺",
        coords: [26.2456, 105.9322],
        spots: ["Huangguoshu Waterfall", "Tianxingqiao Scenic Area"],
        spotsLocal: ["黄果树瀑布", "天星桥景区"],
        photos: [
          { src: "img/guizhou/anshun-tianxingqiao-water-trail.jpg", caption: "Anshun / 安顺 - Tianxingqiao Scenic Area / 天星桥景区 - Water Trail" },
          { src: "img/guizhou/anshun-tianxingqiao-bridge-view.jpg", caption: "Anshun / 安顺 - Tianxingqiao Scenic Area / 天星桥景区 - Bridge View" },
          { src: "img/guizhou/anshun-huangguoshu-waterfall-mist-view.jpg", caption: "Anshun / 安顺 - Huangguoshu Waterfall / 黄果树瀑布 - Mist View" },
          { src: "img/guizhou/anshun-huangguoshu-waterfall-wide-view.jpg", caption: "Anshun / 安顺 - Huangguoshu Waterfall / 黄果树瀑布 - Wide View" }
        ]
      },
      {
        region: "Shandong",
        name: "Qingdao",
        localName: "青岛",
        coords: [36.0671, 120.3826],
        spots: ["Laoshan"],
        spotsLocal: ["崂山"],
        photos: [
          { src: "img/shandong/qingdao-park-lake-tower.jpg", caption: "Qingdao / 青岛 - Park Lake Tower" },
          { src: "img/shandong/qingdao-laoshan-mountain-view.jpg", caption: "Qingdao / 青岛 - Laoshan / 崂山 - Mountain View" },
          { src: "img/shandong/qingdao-laoshan-cloudy-hills.jpg", caption: "Qingdao / 青岛 - Laoshan / 崂山 - Cloudy Hills" },
          { src: "img/shandong/qingdao-laoshan-forest-walk.jpg", caption: "Qingdao / 青岛 - Laoshan / 崂山 - Forest Walk" },
          { src: "img/shandong/qingdao-laoshan-monkey.jpg", caption: "Qingdao / 青岛 - Laoshan / 崂山 - Monkey" },
          { src: "img/shandong/qingdao-laoshan-mountain-stream.jpg", caption: "Qingdao / 青岛 - Laoshan / 崂山 - Mountain Stream" },
          { src: "img/shandong/qingdao-laoshan-gorge-view.jpg", caption: "Qingdao / 青岛 - Laoshan / 崂山 - Gorge View" }
        ]
      },
      { region: "Shandong", name: "Gaomi", localName: "高密", coords: [36.3833, 119.7520], spots: ["Mo Yan Former Residence", "Gaomi City Museum"], spotsLocal: ["莫言旧居", "高密市博物馆"] },
      { region: "Fujian", name: "Fuzhou", localName: "福州", coords: [26.0745, 119.2965], spots: ["Three Lanes and Seven Alleys", "West Lake Park"], spotsLocal: ["三坊七巷", "西湖公园"] },
      { region: "Hubei", name: "Wuhan", localName: "武汉", coords: [30.5928, 114.3055], spots: ["Yellow Crane Tower", "East Lake", "Wuhan Yangtze River Bridge"], spotsLocal: ["黄鹤楼", "东湖", "武汉长江大桥"] },
      {
        region: "Jilin",
        name: "Changchun",
        localName: "长春",
        coords: [43.8171, 125.3235],
        spots: ["Puppet Emperor's Palace Museum", "Jingyuetan National Forest Park", "City Streets"],
        spotsLocal: ["伪满皇宫博物院", "净月潭国家森林公园", "城市街景"],
        photos: [
          { src: "img/jilin/changchun-puppet-emperors-palace-museum-gate.jpg", caption: "Changchun / 长春 - Puppet Emperor's Palace Museum / 伪满皇宫博物院 - Gate" },
          { src: "img/jilin/changchun-puppet-emperors-palace-museum-chandelier.jpg", caption: "Changchun / 长春 - Puppet Emperor's Palace Museum / 伪满皇宫博物院 - Chandelier" },
          { src: "img/jilin/changchun-puppet-emperors-palace-museum-interior-room.jpg", caption: "Changchun / 长春 - Puppet Emperor's Palace Museum / 伪满皇宫博物院 - Interior Room" },
          { src: "img/jilin/changchun-puppet-emperors-palace-museum-corridor-view.jpg", caption: "Changchun / 长春 - Puppet Emperor's Palace Museum / 伪满皇宫博物院 - Corridor View" },
          { src: "img/jilin/changchun-puppet-emperors-palace-museum-historical-document.jpg", caption: "Changchun / 长春 - Puppet Emperor's Palace Museum / 伪满皇宫博物院 - Historical Document" },
          { src: "img/jilin/changchun-puppet-emperors-palace-museum-exhibition-flag.jpg", caption: "Changchun / 长春 - Puppet Emperor's Palace Museum / 伪满皇宫博物院 - Exhibition Flag" },
          { src: "img/jilin/changchun-puppet-emperors-palace-museum-throne-room.jpg", caption: "Changchun / 长春 - Puppet Emperor's Palace Museum / 伪满皇宫博物院 - Throne Room" },
          { src: "img/jilin/changchun-puppet-emperors-palace-museum-palace-roof.jpg", caption: "Changchun / 长春 - Puppet Emperor's Palace Museum / 伪满皇宫博物院 - Palace Roof" },
          { src: "img/jilin/changchun-puppet-emperors-palace-museum-roof-detail.jpg", caption: "Changchun / 长春 - Puppet Emperor's Palace Museum / 伪满皇宫博物院 - Roof Detail" },
          { src: "img/jilin/changchun-city-road.jpg", caption: "Changchun / 长春 - City Road" },
          { src: "img/jilin/changchun-monument-sculpture.jpg", caption: "Changchun / 长春 - Monument Sculpture" },
          { src: "img/jilin/changchun-monument-building.jpg", caption: "Changchun / 长春 - Monument Building" },
          { src: "img/jilin/changchun-red-brick-building.jpg", caption: "Changchun / 长春 - Red Brick Building" },
          { src: "img/jilin/changchun-museum-vehicle.jpg", caption: "Changchun / 长春 - Museum Vehicle" },
          { src: "img/jilin/changchun-night-street.jpg", caption: "Changchun / 长春 - Night Street" }
        ]
      },
      { region: "Jilin", name: "Songyuan", localName: "松原", coords: [45.1411, 124.8251], spots: ["Chagan Lake", "Songyuan Museum"], spotsLocal: ["查干湖", "松原市博物馆"] },
      {
        region: "Liaoning",
        name: "Shenyang",
        localName: "沈阳",
        coords: [41.8057, 123.4315],
        spots: ["Shenyang Imperial Palace", "Marshal Zhang's Mansion", "Liaoning Provincial Museum"],
        spotsLocal: ["沈阳故宫", "张氏帅府", "辽宁省博物馆"],
        photos: [
          { src: "img/liaoning/shenyang-museum-facade.jpg", caption: "Shenyang / 沈阳 - Museum Facade" },
          { src: "img/liaoning/shenyang-historical-painting.jpg", caption: "Shenyang / 沈阳 - Historical Painting" },
          { src: "img/liaoning/shenyang-imperial-palace-courtyard.jpg", caption: "Shenyang / 沈阳 - Shenyang Imperial Palace / 沈阳故宫 - Courtyard" },
          { src: "img/liaoning/shenyang-imperial-palace-gate.jpg", caption: "Shenyang / 沈阳 - Shenyang Imperial Palace / 沈阳故宫 - Palace Gate" },
          { src: "img/liaoning/shenyang-imperial-palace-interior-detail.jpg", caption: "Shenyang / 沈阳 - Shenyang Imperial Palace / 沈阳故宫 - Interior Detail" },
          { src: "img/liaoning/shenyang-imperial-palace-hall.jpg", caption: "Shenyang / 沈阳 - Shenyang Imperial Palace / 沈阳故宫 - Palace Hall" },
          { src: "img/liaoning/shenyang-imperial-palace-painted-column.jpg", caption: "Shenyang / 沈阳 - Shenyang Imperial Palace / 沈阳故宫 - Painted Column" },
          { src: "img/liaoning/shenyang-imperial-palace-roofline.jpg", caption: "Shenyang / 沈阳 - Shenyang Imperial Palace / 沈阳故宫 - Roofline" },
          { src: "img/liaoning/shenyang-imperial-palace-door-plaque.jpg", caption: "Shenyang / 沈阳 - Shenyang Imperial Palace / 沈阳故宫 - Door Plaque" },
          { src: "img/liaoning/shenyang-museum-artifact.jpg", caption: "Shenyang / 沈阳 - Museum Artifact" },
          { src: "img/liaoning/shenyang-marshal-zhangs-mansion-exterior.jpg", caption: "Shenyang / 沈阳 - Marshal Zhang's Mansion / 张氏帅府 - Exterior" },
          { src: "img/liaoning/shenyang-interior-pattern.jpg", caption: "Shenyang / 沈阳 - Interior Pattern" },
          { src: "img/liaoning/shenyang-marshal-zhangs-mansion-interior-room.jpg", caption: "Shenyang / 沈阳 - Marshal Zhang's Mansion / 张氏帅府 - Interior Room" },
          { src: "img/liaoning/shenyang-marshal-zhangs-mansion-meeting-room.jpg", caption: "Shenyang / 沈阳 - Marshal Zhang's Mansion / 张氏帅府 - Meeting Room" },
          { src: "img/liaoning/shenyang-marshal-zhangs-mansion-study-room.jpg", caption: "Shenyang / 沈阳 - Marshal Zhang's Mansion / 张氏帅府 - Study Room" },
          { src: "img/liaoning/shenyang-museum-sculpture.jpg", caption: "Shenyang / 沈阳 - Museum Sculpture" },
          { src: "img/liaoning/shenyang-museum-artifact-2.jpg", caption: "Shenyang / 沈阳 - Museum Artifact" },
          { src: "img/liaoning/shenyang-museum-artifacts.jpg", caption: "Shenyang / 沈阳 - Museum Artifacts" },
          { src: "img/liaoning/shenyang-museum-figure.jpg", caption: "Shenyang / 沈阳 - Museum Figure" },
          { src: "img/liaoning/shenyang-ceramic-vase.jpg", caption: "Shenyang / 沈阳 - Ceramic Vase" },
          { src: "img/liaoning/shenyang-palace-plaque-detail.jpg", caption: "Shenyang / 沈阳 - Palace Plaque Detail" }
        ]
      }
    ],
    regionLocalNames: {
      Singapore: "新加坡",
      Japan: "日本",
      Brunei: "نڬارا بروني دارالسلام",
      Malaysia: "مليسيا",
      Laos: "ລາວ",
      Cambodia: "កម្ពុជា",
      Indonesia: "Republik Indonesia",
      Vietnam: "Việt Nam",
      Thailand: "ประเทศไทย",
      Taiwan: "臺灣",
      Yunnan: "云南",
      Guizhou: "贵州",
      Shandong: "山东",
      Fujian: "福建",
      Hubei: "湖北",
      Jilin: "吉林",
      Liaoning: "辽宁"
    },
    photoOrientations: {
      "img/cambodia/phnom-penh-choeung-ek-fields-skyline.jpg": "landscape",
      "img/cambodia/phnom-penh-choeung-ek-memorial-quote.jpg": "landscape",
      "img/cambodia/phnom-penh-choeung-ek-memorial-statue.jpg": "portrait",
      "img/cambodia/phnom-penh-choeung-ek-memorial-stupa.jpg": "portrait",
      "img/cambodia/phnom-penh-choeung-ek-remembrance-tree.jpg": "portrait",
      "img/cambodia/phnom-penh-city-skyline.jpg": "landscape",
      "img/cambodia/phnom-penh-evening-traffic.jpg": "portrait",
      "img/cambodia/phnom-penh-independence-monument.jpg": "portrait",
      "img/cambodia/phnom-penh-mekong-river-skyline.jpg": "portrait",
      "img/cambodia/phnom-penh-national-museum-courtyard-pond.jpg": "landscape",
      "img/cambodia/phnom-penh-national-museum-flag-detail.jpg": "landscape",
      "img/cambodia/phnom-penh-national-museum-gallery.jpg": "portrait",
      "img/cambodia/phnom-penh-river-birds.jpg": "landscape",
      "img/cambodia/phnom-penh-riverside-cattle.jpg": "landscape",
      "img/cambodia/phnom-penh-riverside-pigeons.jpg": "landscape",
      "img/cambodia/phnom-penh-royal-palace-garden-walk.jpg": "portrait",
      "img/cambodia/phnom-penh-royal-palace-roof-detail.jpg": "portrait",
      "img/cambodia/phnom-penh-royal-palace-spire.jpg": "portrait",
      "img/cambodia/phnom-penh-royal-palace-temple-roof.jpg": "portrait",
      "img/cambodia/phnom-penh-royal-palace-throne-hall.jpg": "portrait",
      "img/cambodia/phnom-penh-silver-pagoda-stupa-statue.jpg": "landscape",
      "img/cambodia/phnom-penh-silver-pagoda-white-stupa.jpg": "landscape",
      "img/cambodia/phnom-penh-street-balconies.jpg": "portrait",
      "img/cambodia/phnom-penh-tuol-sleng-artwork.jpg": "landscape",
      "img/cambodia/phnom-penh-tuol-sleng-cell-block.jpg": "portrait",
      "img/cambodia/phnom-penh-tuol-sleng-corridor.jpg": "portrait",
      "img/cambodia/phnom-penh-tuol-sleng-drawing.jpg": "landscape",
      "img/cambodia/phnom-penh-tuol-sleng-exhibit-wall.jpg": "landscape",
      "img/cambodia/phnom-penh-tuol-sleng-room.jpg": "landscape",
      "img/cambodia/phnom-penh-wat-phnom-shrine-entrance.jpg": "portrait",
      "img/cambodia/phnom-penh-wat-phnom-white-stupa.jpg": "portrait",
      "img/guizhou/anshun-huangguoshu-waterfall-mist-view.jpg": "landscape",
      "img/guizhou/anshun-huangguoshu-waterfall-wide-view.jpg": "landscape",
      "img/guizhou/anshun-tianxingqiao-bridge-view.jpg": "landscape",
      "img/guizhou/anshun-tianxingqiao-water-trail.jpg": "landscape",
      "img/guizhou/guiyang-memorial-grounds.jpg": "portrait",
      "img/guizhou/guiyang-temple-courtyard.jpg": "portrait",
      "img/guizhou/guiyang-xifeng-concentration-camp.jpg": "portrait",
      "img/guizhou/renhuai-maotai-town-green-hills.jpg": "portrait",
      "img/guizhou/renhuai-maotai-town-hillside-view.jpg": "landscape",
      "img/guizhou/renhuai-maotai-town-mountain-town.jpg": "landscape",
      "img/guizhou/renhuai-maotai-town-red-bridge.jpg": "landscape",
      "img/guizhou/renhuai-maotai-town-river-valley.jpg": "landscape",
      "img/guizhou/renhuai-maotai-town-riverside-buildings.jpg": "landscape",
      "img/guizhou/zunyi-city-view.jpg": "portrait",
      "img/guizhou/zunyi-conference-site.jpg": "landscape",
      "img/guizhou/zunyi-exhibition-detail.jpg": "landscape",
      "img/guizhou/zunyi-historical-document.jpg": "landscape",
      "img/guizhou/zunyi-historical-exhibition.jpg": "portrait",
      "img/guizhou/zunyi-mao-zedong-residence.jpg": "portrait",
      "img/guizhou/zunyi-museum-artifact.jpg": "landscape",
      "img/japan/osaka-city-museum-city-view.jpg": "portrait",
      "img/japan/osaka-keitakuen-autumn-maples.jpg": "landscape",
      "img/japan/osaka-keitakuen-garden-bridge.jpg": "portrait",
      "img/japan/osaka-keitakuen-garden-reflection.jpg": "landscape",
      "img/japan/osaka-keitakuen-maple-leaves.jpg": "portrait",
      "img/japan/osaka-keitakuen-water-reflection.jpg": "landscape",
      "img/japan/osaka-nagai-botanical-autumn-leaves.jpg": "portrait",
      "img/japan/osaka-nagai-botanical-branches.jpg": "portrait",
      "img/japan/osaka-nagai-botanical-camellia.jpg": "portrait",
      "img/japan/osaka-nagai-botanical-cherry-blossoms.jpg": "landscape",
      "img/japan/osaka-nagai-botanical-lake-fountain.jpg": "landscape",
      "img/japan/osaka-nagai-botanical-red-bridge.jpg": "portrait",
      "img/japan/osaka-nagai-botanical-tree-path.jpg": "portrait",
      "img/japan/osaka-nagai-botanical-water-view.jpg": "portrait",
      "img/japan/osaka-nagai-botanical-waterfall.jpg": "portrait",
      "img/japan/osaka-nagai-botanical-white-blossoms.jpg": "portrait",
      "img/japan/osaka-nagai-botanical-winter-garden.jpg": "portrait",
      "img/japan/osaka-river-tower-sunset-skyline.jpg": "landscape",
      "img/japan/osaka-river-tower-window-view.jpg": "landscape",
      "img/japan/osaka-shinsekai-tsutenkaku.jpg": "portrait",
      "img/japan/osaka-shitennoji-five-story-pagoda.jpg": "portrait",
      "img/japan/osaka-tennoji-zoo-deer.jpg": "portrait",
      "img/japan/osaka-tennoji-zoo-flamingos.jpg": "portrait",
      "img/japan/osaka-tennoji-zoo-habitat-waterfall.jpg": "landscape",
      "img/japan/osaka-tennoji-zoo-tiger.jpg": "landscape",
      "img/japan/osaka-tennoji-zoo-zebra.jpg": "landscape",
      "img/jilin/changchun-city-road.jpg": "landscape",
      "img/jilin/changchun-monument-building.jpg": "landscape",
      "img/jilin/changchun-monument-sculpture.jpg": "landscape",
      "img/jilin/changchun-museum-vehicle.jpg": "landscape",
      "img/jilin/changchun-night-street.jpg": "landscape",
      "img/jilin/changchun-puppet-emperors-palace-museum-chandelier.jpg": "landscape",
      "img/jilin/changchun-puppet-emperors-palace-museum-corridor-view.jpg": "landscape",
      "img/jilin/changchun-puppet-emperors-palace-museum-exhibition-flag.jpg": "landscape",
      "img/jilin/changchun-puppet-emperors-palace-museum-gate.jpg": "portrait",
      "img/jilin/changchun-puppet-emperors-palace-museum-historical-document.jpg": "landscape",
      "img/jilin/changchun-puppet-emperors-palace-museum-interior-room.jpg": "landscape",
      "img/jilin/changchun-puppet-emperors-palace-museum-palace-roof.jpg": "portrait",
      "img/jilin/changchun-puppet-emperors-palace-museum-roof-detail.jpg": "portrait",
      "img/jilin/changchun-puppet-emperors-palace-museum-throne-room.jpg": "landscape",
      "img/jilin/changchun-red-brick-building.jpg": "landscape",
      "img/laos/vientiane-patuxai-arch-detail.jpg": "portrait",
      "img/laos/vientiane-patuxai-monument-front.jpg": "portrait",
      "img/laos/vientiane-pha-that-luang-golden-stupa-detail.jpg": "portrait",
      "img/laos/vientiane-pha-that-luang-golden-stupa.jpg": "portrait",
      "img/laos/vientiane-pha-that-luang-silhouette.jpg": "landscape",
      "img/liaoning/shenyang-ceramic-vase.jpg": "portrait",
      "img/liaoning/shenyang-historical-painting.jpg": "landscape",
      "img/liaoning/shenyang-imperial-palace-courtyard.jpg": "landscape",
      "img/liaoning/shenyang-imperial-palace-door-plaque.jpg": "portrait",
      "img/liaoning/shenyang-imperial-palace-gate.jpg": "landscape",
      "img/liaoning/shenyang-imperial-palace-hall.jpg": "landscape",
      "img/liaoning/shenyang-imperial-palace-interior-detail.jpg": "portrait",
      "img/liaoning/shenyang-imperial-palace-painted-column.jpg": "landscape",
      "img/liaoning/shenyang-imperial-palace-roofline.jpg": "landscape",
      "img/liaoning/shenyang-interior-pattern.jpg": "landscape",
      "img/liaoning/shenyang-marshal-zhangs-mansion-exterior.jpg": "landscape",
      "img/liaoning/shenyang-marshal-zhangs-mansion-interior-room.jpg": "landscape",
      "img/liaoning/shenyang-marshal-zhangs-mansion-meeting-room.jpg": "landscape",
      "img/liaoning/shenyang-marshal-zhangs-mansion-study-room.jpg": "landscape",
      "img/liaoning/shenyang-museum-artifact-2.jpg": "landscape",
      "img/liaoning/shenyang-museum-artifact.jpg": "portrait",
      "img/liaoning/shenyang-museum-artifacts.jpg": "landscape",
      "img/liaoning/shenyang-museum-facade.jpg": "landscape",
      "img/liaoning/shenyang-museum-figure.jpg": "landscape",
      "img/liaoning/shenyang-museum-sculpture.jpg": "landscape",
      "img/liaoning/shenyang-palace-plaque-detail.jpg": "landscape",
      "img/nevada/las-vegas-arte-museum-floral-room.jpg": "landscape",
      "img/nevada/las-vegas-arte-museum-flower-lights.jpg": "landscape",
      "img/nevada/las-vegas-arte-museum-immersive-room.jpg": "landscape",
      "img/shandong/qingdao-laoshan-cloudy-hills.jpg": "landscape",
      "img/shandong/qingdao-laoshan-forest-walk.jpg": "portrait",
      "img/shandong/qingdao-laoshan-gorge-view.jpg": "portrait",
      "img/shandong/qingdao-laoshan-monkey.jpg": "portrait",
      "img/shandong/qingdao-laoshan-mountain-stream.jpg": "landscape",
      "img/shandong/qingdao-laoshan-mountain-view.jpg": "landscape",
      "img/shandong/qingdao-park-lake-tower.jpg": "portrait",
      "img/taiwan/anping-fort-watchtower.jpg": "portrait",
      "img/taiwan/chimei-museum-exterior.jpg": "portrait",
      "img/taiwan/chimei-museum-interior.jpg": "portrait",
      "img/taiwan/grand-hotel-taipei-ceiling.jpg": "portrait",
      "img/taiwan/grand-hotel-taipei-christmas-tree.jpg": "portrait",
      "img/taiwan/grand-hotel-taipei-rainy-skyline.jpg": "portrait",
      "img/taiwan/sun-moon-lake-lake-view.jpg": "landscape",
      "img/taiwan/sun-moon-lake-lakeside-sculpture.jpg": "portrait",
      "img/taiwan/sun-moon-lake-pagoda-view.jpg": "portrait",
      "img/taiwan/sun-moon-lake-temple-view.jpg": "portrait",
      "img/taiwan/sun-moon-lake-trail.jpg": "portrait",
      "img/vietnam/hanoi-fine-arts-lacquer-panel.jpg": "landscape",
      "img/vietnam/hanoi-fine-arts-museum-building.jpg": "landscape",
      "img/vietnam/hanoi-fine-arts-museum-gallery.jpg": "portrait",
      "img/vietnam/hanoi-fine-arts-museum-interior.jpg": "portrait",
      "img/vietnam/hanoi-fine-arts-painting-harbor.jpg": "landscape",
      "img/vietnam/hanoi-fine-arts-painting-scene.jpg": "landscape",
      "img/vietnam/hanoi-flag-tower.jpg": "portrait",
      "img/vietnam/hanoi-ho-chi-minh-mausoleum.jpg": "portrait",
      "img/vietnam/hanoi-hoan-kiem-lake-flowers.jpg": "landscape",
      "img/vietnam/hanoi-hoan-kiem-lake-shore.jpg": "portrait",
      "img/vietnam/hanoi-hoan-kiem-lake-turtle-tower.jpg": "portrait",
      "img/vietnam/hanoi-hoan-kiem-lake-yellow-colonial-building.jpg": "portrait",
      "img/vietnam/hanoi-lenin-statue.jpg": "landscape",
      "img/vietnam/hanoi-military-history-museum-aircraft.jpg": "landscape",
      "img/vietnam/hanoi-museum-facade.jpg": "landscape",
      "img/vietnam/hanoi-old-gate.jpg": "portrait",
      "img/vietnam/hanoi-old-quarter-lanterns-building.jpg": "landscape",
      "img/vietnam/hanoi-old-quarter-red-lanterns.jpg": "portrait",
      "img/vietnam/hanoi-one-pillar-pagoda.jpg": "portrait",
      "img/vietnam/hanoi-st-joseph-cathedral.jpg": "portrait",
      "img/vietnam/hanoi-temple-gate.jpg": "portrait",
      "img/vietnam/hanoi-temple-of-literature-gate.jpg": "portrait",
      "img/vietnam/hanoi-war-memorial-monument.jpg": "portrait",
      "img/vietnam/ho-chi-minh-city-alley.jpg": "portrait",
      "img/vietnam/ho-chi-minh-city-ben-thanh-market-hats.jpg": "landscape",
      "img/vietnam/ho-chi-minh-city-central-post-office-exterior.jpg": "portrait",
      "img/vietnam/ho-chi-minh-city-central-post-office-interior.jpg": "landscape",
      "img/vietnam/ho-chi-minh-city-museum-facade.jpg": "landscape",
      "img/vietnam/ho-chi-minh-city-museum-historical-photo.jpg": "landscape",
      "img/vietnam/ho-chi-minh-city-museum-inscription.jpg": "portrait",
      "img/vietnam/ho-chi-minh-city-night-skyline.jpg": "landscape",
      "img/vietnam/ho-chi-minh-city-park-gate.jpg": "portrait",
      "img/yunnan/dali-erhai-lake-lakeside-view.jpg": "portrait",
      "img/yunnan/dali-erhai-lake-mountain-horizon.jpg": "landscape",
      "img/yunnan/dali-erhai-lake-water-and-mountains.jpg": "landscape",
      "img/yunnan/kunming-garden-lake-view.jpg": "portrait",
      "img/yunnan/kunming-stone-forest-karst-passage.jpg": "portrait",
      "img/yunnan/kunming-stone-forest-mossy-path.jpg": "portrait",
      "img/yunnan/kunming-stone-forest-rock-window.jpg": "portrait",
      "img/yunnan/lijiang-blue-moon-valley-clear-pool.jpg": "portrait",
      "img/yunnan/lijiang-blue-moon-valley-mountain-stream.jpg": "portrait",
      "img/yunnan/lijiang-blue-moon-valley-turquoise-water.jpg": "portrait",
      "img/yunnan/lijiang-blue-moon-valley-waterfall-steps.jpg": "landscape",
      "img/yunnan/lijiang-evening-city-view.jpg": "landscape",
      "img/yunnan/lijiang-jade-dragon-snow-mountain-cloudy-meadow.jpg": "landscape",
      "img/yunnan/lijiang-jade-dragon-snow-mountain-forest-canopy.jpg": "portrait",
      "img/yunnan/lijiang-jade-dragon-snow-mountain-forest-walk.jpg": "portrait",
      "img/yunnan/lijiang-jade-dragon-snow-mountain-glacier-view.jpg": "landscape",
      "img/yunnan/lijiang-jade-dragon-snow-mountain-glacier.jpg": "landscape",
      "img/yunnan/lijiang-jade-dragon-snow-mountain-highland-meadow.jpg": "portrait",
      "img/yunnan/lijiang-jade-dragon-snow-mountain-misty-peak.jpg": "landscape",
      "img/yunnan/lijiang-jade-dragon-snow-mountain-valley-view.jpg": "landscape",
      "img/yunnan/lijiang-jade-dragon-snow-mountain-yak-trail.jpg": "portrait",
      "img/yunnan/lijiang-mountain-city-view.jpg": "landscape"
    }
  };
})();
